---
- name: Install parted and disk utils
  ansible.builtin.package:
    name:
      - parted
      - "{{ (ansible_os_family == 'Debian') | ternary('scsitools', 'sg3_utils') }}"
    state: present

- name: Install additional fs progs
  ansible.builtin.package:
    name: "{{ disk_additional_fs_utils }}"
    state: present
  when:
    - disk_additional_fs_utils | length > 0

- name: Checking for scsi devices
  ansible.builtin.command: |
    sg_scan
  changed_when: false
  check_mode: false
  register: scsi_devices

- name: Rescan SCSI disks
  ansible.builtin.shell: |
    /sbin/rescan-scsi-bus --forcerescan || /usr/bin/rescan-scsi-bus.sh --forcerescan
  changed_when: false
  when:
    - scsi_devices.stdout != ''

- name: Whole disk usage
  ansible.builtin.include_tasks: disk-loop.yml
  loop: "{{ disk_additional_disks }}"
  when:
    - item.parts is undefined

- name: Part disk usage
  ansible.builtin.include_tasks: disk-loop-parts.yml
  loop: "{{ disk_additional_disks }}"
  when:
    - item.parts is defined
