---
# Handlers for services
- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen:
    - restart systemd-resolved

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    masked: false
    state: restarted
  listen:
    - restart systemd-resolved
