---
# handlers file for timesyncd

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen:
    - restart systemd-timesyncd

- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    masked: false
    state: restarted
  listen:
    - restart systemd-timesyncd

- name: Update timezone
  ansible.builtin.command: |
    dpkg-reconfigure tzdata
  environment:
    DEBIAN_FRONTEND: noninteractive
  changed_when: false
  listen:
    - update timezone
