---
- name: Install systemd-component
  ansible.builtin.apt:
    name:
      - systemd-resolved
    state: present
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Change DNS server and settings at /etc/systemd/resolved.conf
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    force: true
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart systemd-resolved
  when:
    - dns_servers is defined

- name: Ensure dns handlers are flushed
  ansible.builtin.meta: flush_handlers
