---
- name: Install cli tools
  ansible.builtin.apt:
    name:
      - ethtool
      - hdparm
      - util-linux
    state: present
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
  environment:
    DEBIAN_FRONTEND: noninteractive
  check_mode: false

- name: Create udev rules
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/udev/rules.d/{{ item | basename | regex_replace('.j2', '') }}"
    backup: false
    owner: root
    group: root
    mode: "0644"
  with_fileglob:
    - templates/*.rules.j2
  notify:
    - update udev rules

- name: Ensure udev handlers are flushed
  ansible.builtin.meta: flush_handlers
