---
- name: centos | installing lvm2
  ansible.builtin.package:
    name: lvm2
    state: present

- name: centos | installing sg3_utils
  ansible.builtin.package:
    name: sg3_utils
    state: present

- name: centos | debug lvg
  ansible.builtin.debug:
    var: lv
    verbosity: 3
  loop: "{{ lookup('subelements', lvm_groups, 'lvnames', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    loop_var: lv

- name: centos | install xfs tools
  ansible.builtin.package:
    name: "xfsprogs"
    state: "present"
  loop: "{{ lookup('subelements', lvm_groups, 'lvnames', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    loop_var: lv
  when:
    - lv.1 is defined
    - lv.1 != "None"
    - lv.1.filesystem is defined
    - lv.1.filesystem == "xfs"
    - lv.1.create is defined
    - lv.1.create|bool

- name: centos | checking for scsi devices
  ansible.builtin.command: sg_scan
  register: scsi_devices
  changed_when: false

- name: centos | rescanning for new disks
  ansible.builtin.command: /usr/bin/rescan-scsi-bus.sh
  changed_when: false
